 /*Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms 
 will be :1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million,find the sum of the even - valued terms.
 求400万以内的斐波那契数列中所有偶数的和。（答案：4613732 ）*/

#include <iostream>
using namespace std;

int Fibonacci(int v1, int v2)
{
	int v3 = v1 + v2;
	return v3;
}
int main()
{
	int sum = 2,v1=1,v2=2,v3=v1+v2;
	while ( v3< 4000000)
	{
		if(!(v3% 2))
		{
			sum+=v3;
			/*break*/;
		}
		v1 = v2;
		v2 = v3;
		v3 = Fibonacci(v1, v2);
	}
	cout << sum << endl;
	return 0;
}
